version: '3.7'


services:
  database_register_client:
    image: postgres
    container_name: database_register_client
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=database_register_client
    volumes:
      - pgdata:/data/postgres
    
  app:
    build: .
    container_name: server
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_register_client
    depends_on:
      - database_register_client

volumes:
  pgdata:
    driver: local